<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="118895" started-at="2018-04-29T17:47:01Z" finished-at="2018-04-29T17:49:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="118895" started-at="2018-04-29T17:47:01Z" finished-at="2018-04-29T17:49:00Z">
      <class name="testAllure2.CreatingAccount">
        <test-method status="PASS" signature="createAcc()[pri:0, instance:testAllure2.CreatingAccount@530612ba]" name="createAcc" duration-ms="46467" started-at="2018-04-29T23:17:01Z" description="creating the account" finished-at="2018-04-29T23:17:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAcc -->
        <test-method status="PASS" signature="modifyAcc()[pri:0, instance:testAllure2.CreatingAccount@530612ba]" name="modifyAcc" duration-ms="36646" started-at="2018-04-29T23:17:48Z" description="updating the account" finished-at="2018-04-29T23:18:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifyAcc -->
        <test-method status="FAIL" signature="deleteAcc()[pri:0, instance:testAllure2.CreatingAccount@530612ba]" name="deleteAcc" duration-ms="35332" started-at="2018-04-29T23:18:25Z" description="deleting the account" finished-at="2018-04-29T23:19:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Meet Guru99 - Free Training Tutorials & Video for IT Courses] but found [guru]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Meet Guru99 - Free Training Tutorials & Video for IT Courses] but found [guru]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at testAllure2.CreatingAccount.deleteAcc(CreatingAccount.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteAcc -->
      </class> <!-- testAllure2.CreatingAccount -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
